title: Noosh
author: Noosh
email: Noosh
description: > # this means to ignore newlines until "baseurl:"
  da bes

# social links
twitter_username: da bes
github_username:  da bes
show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
